version: '3.8'

services:

  app:

    image: ghcr.io/19ramirez/docker-flask:1.0.0

    container_name: docker-flask

    ports:
      - "5000:5000"

    depends_on:
      - db

volumes:
  postgres_data: