version: '3.8'

services:
  app:
    image: ghcr.io/19ramirez/docker-flask:1.0.0
    networks:
      - traefik-public
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.tecticom.entrypoints=http"
        # AQUÍ AGREGAMOS AMBOS DOMINIOS SEPARADOS POR ||
        - "traefik.http.routers.tecticom.rule=Host(`1750002782.byronrm.com`) || Host(`tecticom.byronrm.com`)"
        - "traefik.http.middlewares.tecticom-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.tecticom.middlewares=tecticom-https-redirect"
        - "traefik.http.routers.tecticom-secure.entrypoints=https"
        # AQUÍ TAMBIÉN REPETIMOS EN LA REGLA SEGURA (HTTPS)
        - "traefik.http.routers.tecticom-secure.rule=Host(`1750002782.byronrm.com`) || Host(`tecticom.byronrm.com`)"
        - "traefik.http.routers.tecticom-secure.tls=true"
        - "traefik.http.routers.tecticom-secure.tls.certresolver=http"
        - "traefik.http.routers.tecticom-secure.service=tecticom"
        - "traefik.http.services.tecticom.loadbalancer.server.port=5000"
        - "traefik.docker.network=traefik-public"

networks:
  traefik-public:
    external: true