version: '3.8'

services:
  app:
    image: ghcr.io/19ramirez/docker-flask:1.0.0
    networks:
      - traefik-public
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        # Configuramos los routers y servicios usando tu cédula para evitar colisiones
        - "traefik.http.routers.r1750002782.entrypoints=http"
        - "traefik.http.routers.r1750002782.rule=Host(`1750002782.byronrm.com`)"
        - "traefik.http.middlewares.m1750002782-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.r1750002782.middlewares=m1750002782-https-redirect"
        - "traefik.http.routers.r1750002782-secure.entrypoints=https"
        - "traefik.http.routers.r1750002782-secure.rule=Host(`1750002782.byronrm.com`)"
        - "traefik.http.routers.r1750002782-secure.tls=true"
        - "traefik.http.routers.r1750002782-secure.tls.certresolver=http"
        - "traefik.http.routers.r1750002782-secure.service=s1750002782"
        - "traefik.http.services.s1750002782.loadbalancer.server.port=5000"
        - "traefik.docker.network=traefik-public"

networks:
  traefik-public:
    external: true